version: '3.8'

services:
  user-database:
    image: postgres:16
    container_name: gestock-user-db
    environment:
      POSTGRES_USER: gestock
      POSTGRES_PASSWORD: 56ad72bb-0ef4-473b-ae9e-d6cf8d2dced4
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
